// Mocks generated by Mockito 5.4.6 from annotations
// in restaurant_app/test/unit_test/provider/restaurant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_app/src/core/core.dart' as _i3;
import 'package:restaurant_app/src/features/restaurant/domain/entity/entity.dart'
    as _i6;
import 'package:restaurant_app/src/features/restaurant/domain/repository/restaurant_repository.dart'
    as _i2;
import 'package:restaurant_app/src/features/restaurant/domain/usecase/get_restaurants_usecase.dart'
    as _i4;
import 'package:restaurant_app/src/features/restaurant/domain/usecase/get_search_restaurants_usecase.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRestaurantRepository_0 extends _i1.SmartFake
    implements _i2.RestaurantRepository {
  _FakeRestaurantRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetRestaurantsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRestaurantsUseCase extends _i1.Mock
    implements _i4.GetRestaurantsUseCase {
  MockGetRestaurantsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestaurantRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRestaurantRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RestaurantRepository);

  @override
  _i5.Future<_i3.Either<_i3.AppError, _i6.RestaurantEntity>> call(
    _i3.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i3.AppError, _i6.RestaurantEntity>
                >.value(
                  _FakeEither_1<_i3.AppError, _i6.RestaurantEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i3.AppError, _i6.RestaurantEntity>>);
}

/// A class which mocks [GetSearchRestaurantsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchRestaurantsUsecase extends _i1.Mock
    implements _i7.GetSearchRestaurantsUsecase {
  MockGetSearchRestaurantsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestaurantRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRestaurantRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RestaurantRepository);

  @override
  _i5.Future<_i3.Either<_i3.AppError, _i6.RestaurantEntity>> call(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [query]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i3.AppError, _i6.RestaurantEntity>
                >.value(
                  _FakeEither_1<_i3.AppError, _i6.RestaurantEntity>(
                    this,
                    Invocation.method(#call, [query]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i3.AppError, _i6.RestaurantEntity>>);
}
