// Mocks generated by Mockito 5.4.6 from annotations
// in restaurant_app/test/widget_test/favorite_restaurant_screen_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:restaurant_app/src/core/core.dart' as _i4;
import 'package:restaurant_app/src/features/restaurant/domain/domain.dart'
    as _i2;
import 'package:restaurant_app/src/features/restaurant/presentation/screens/favorite_restaurant/view_model/favorite_restaurant_provider.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFavoriteRestaurantUsecase_0 extends _i1.SmartFake
    implements _i2.FavoriteRestaurantUsecase {
  _FakeFavoriteRestaurantUsecase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FavoriteRestaurantProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRestaurantProvider extends _i1.Mock
    implements _i3.FavoriteRestaurantProvider {
  MockFavoriteRestaurantProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoriteRestaurantUsecase get favoriteRestaurantUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRestaurantUsecase),
            returnValue: _FakeFavoriteRestaurantUsecase_0(
              this,
              Invocation.getter(#favoriteRestaurantUsecase),
            ),
          )
          as _i2.FavoriteRestaurantUsecase);

  @override
  _i4.AppState get favoriteRestaurantState =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRestaurantState),
            returnValue: _i4.AppState.initial,
          )
          as _i4.AppState);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  List<_i2.RestaurantItemEntity> get favoriteRestaurants =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRestaurants),
            returnValue: <_i2.RestaurantItemEntity>[],
          )
          as List<_i2.RestaurantItemEntity>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchFavoriteRestaurants() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFavoriteRestaurants, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void changeAppState(_i4.AppState? state) => super.noSuchMethod(
    Invocation.method(#changeAppState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
